### PR TITLE
[Feature-9449] [Doc] Append how to setting imports for code-style

### PR DESCRIPTION
**Pull request by czeming**
Append how to setting imports for code-style.

https://github.com/apache/dolphinscheduler/issues/9449

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Hi @czeming I think we should add this rule into https://github.com/apache/dolphinscheduler/blob/60457284286b06007c06a1efef7f9706ca848320/style/checkstyle.xml instead of in doc. BTW, does it not exists in our checkstyle now?

**Comment by czeming** [comment]
> Hi @czeming I think we should add this rule into https://github.com/apache/dolphinscheduler/blob/60457284286b06007c06a1efef7f9706ca848320/style/checkstyle.xml instead of in doc. BTW, does it not exists in our checkstyle now?

Yes, it already exists in the current version.

But considering that some developers do not have settings or do not know what they can set, adding documents can provide guidance to set `preferences - > editor - > code style - > java - > imports`.

The default import will be different for different developers. If it is not set, there will be more conflicts or import with *

for example:





Sometimes it can be conflict.

**Comment by zhongjiajie** [comment]
Do not get me wrong, I mean the better way to fix this issue is move your setting into https://github.com/apache/dolphinscheduler-website/pull/779/files#diff-a3045e718256d7ab0a572bebc673b842fdc1ba8ddd8688943177a5674f486559 . and then users could be done all style check config by importing the checke-sytle.xml.

In your case, users have to finish it by two steps:
1. import check-sytle
2. change setting in IDEA.

**Comment by czeming** [comment]
> Do not get me wrong, I mean the better way to fix this issue is move your setting into https://github.com/apache/dolphinscheduler-website/pull/779/files#diff-a3045e718256d7ab0a572bebc673b842fdc1ba8ddd8688943177a5674f486559 . and then users could be done all style check config by importing the checke-sytle.xml.
> 
> In your case, users have to finish it by two steps:
> 
> 1. import check-sytle
> 2. change setting in IDEA.

OK, You mean export the configuration file. I didn't understand before.

---

There is a keyword `JavaCodeStyleSettings` in the configuration file, I didn't find anything in `dolphinscheduler` by searching `JavaCodeStyleSettings`.

I'll add the file to the `dolphinscheduler` and modify this pr to explain how to use it.

**Comment by czeming** [comment]
> Do not get me wrong, I mean the better way to fix this issue is move your setting into https://github.com/apache/dolphinscheduler-website/pull/779/files#diff-a3045e718256d7ab0a572bebc673b842fdc1ba8ddd8688943177a5674f486559 . and then users could be done all style check config by importing the checke-sytle.xml.
> 
> In your case, users have to finish it by two steps:
> 
> 1. import check-sytle
> 2. change setting in IDEA.

Oh! I see, `checksytle.xml` can also be used for `Preferences -> Editor -> Code Style -> Java`.

I thought he was just can used for `Preferences -> Tool -> Checkstyle`.

**Comment by zhongjiajie** [comment]
> > Do not get me wrong, I mean the better way to fix this issue is move your setting into https://github.com/apache/dolphinscheduler-website/pull/779/files#diff-a3045e718256d7ab0a572bebc673b842fdc1ba8ddd8688943177a5674f486559 . and then users could be done all style check config by importing the checke-sytle.xml.
> > In your case, users have to finish it by two steps:
> > 
> > 1. import check-sytle
> > 2. change setting in IDEA.
> 
> Oh! I see, `checksytle.xml` can also be used for `Preferences -> Editor -> Code Style -> Java`.
> 
> I thought it was just can used for `Preferences -> Tool -> Checkstyle`.

Yeah, that is exactly what i mean. Do you want to add it in our `checksytle.xml`

**Pull request closed without merging**
