### PR TITLE
[ci] Fix dead link checker error when new file add

### PR DESCRIPTION
**Pull request by zhongjiajie**
When user add new img or markdown file, our dead link checker would failed, due to we do not have the link in https://github.com/apache/dolphinscheduler-website/blob/6bbcf7f9e85b6cabd452da4813e4a268ffb8346c/.dlc.json#L26-L29 or in https://github.com/apache/dolphinscheduler-website/blob/6bbcf7f9e85b6cabd452da4813e4a268ffb8346c/.dlc.json#L46-L49

BTW, I remove and combine some `ignorePatterns`.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I try to add new img to the repo, it works and dead link checker pass in 1fcb6b1

**Comment by zhongjiajie** [comment]
I try to add the new content file to the repo, it work again in dfb0690

**Review by CalvinKirs — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Thanks

**Comment by CalvinKirs** [comment]
> Thanks
Looking forward to your next contribution

**Pull request merged**
