### PR TITLE
[DS-7193][docs] Modify the problem that the bold in the document does not take effect

### PR DESCRIPTION
**Pull request by SunnyZ-L**
Modify the problem that the bold in the document does not take effect
This closes #7193

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Hi @SunnyZ-L  could you show me the link of our website? I could not find this in our website page.

**Comment by zhongjiajie** [comment]
And, BTW, if we want to change this, please make sure we have to change `en-us`, `dev-zh` and `dev-en` if they have

**Comment by SunnyZ-L** [comment]
> Hi @SunnyZ-L could you show me the link of our website? I could not find this in our website page.

https://github.com/apache/dolphinscheduler-website/pull/562#issuecomment-986387924

**Comment by SunnyZ-L** [comment]
> Hi @SunnyZ-L could you show me the link of our website? I could not find this in our website page.

doc link: https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/architecture/designplus.html
issuse link: https://github.com/apache/dolphinscheduler/issues/7193

> And, BTW, if we want to change this, please make sure we have to change `en-us`, `dev-zh` and `dev-en` if they have

This problem only exists in zh-cn/2.0.0

**Review by zhongjiajie — APPROVED** [review]
LGTM, cc @CalvinKirs

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
