### PR TITLE
Add hyperlinks to documents

### PR DESCRIPTION
**Pull request by jujuAnna**
1、Hyperlink to the basic software section of the Standalone Deployment page
image-20210929211308210
image-20210929211356245
2、Hyperlink to the basic software section of the Cluster Deployment page
image-20210929211553240
image-20210929211634180

### CODE REVIEW

**Comment by CalvinKirs** [comment]
thanks for your contribution, please resolve conflicts files.

**Comment by dailidong** [comment]
great job, thx

Some conflicts need to be solved before merging this PR, the conflicts are as follows:


image

**Comment by dailidong** [comment]
any update?

**Comment by zhongjiajie** [comment]
I add the label `help wanted` for this PR, if some who interested in this, feel free to take it. Do you mind @jujuAnna

**Comment by linjicong** [comment]
I solved the conflicts and submit a new pr.PTAL @zhongjiajie

**Comment by zhongjiajie** [comment]
close this issue due to https://github.com/apache/dolphinscheduler-website/pull/637

**Comment by zhongjiajie** [comment]
Well done @linjicong

**Pull request closed without merging**
