### PR TITLE
[3.0.2-release] Update docs for 3.0.2 release

### PR DESCRIPTION
**Pull request by EricGao888**
* Update website docs for 3.0.2 release

### CODE REVIEW

**Comment by EricGao888** [comment]
@zhongjiajie PTAL : )

**Comment by zhongjiajie** [comment]
maybe we should wait until we release docker image

**Comment by EricGao888** [comment]
> maybe we should wait until we release docker image



> maybe we should wait until we release docker image

Got it, thanks

**Comment by zhongjiajie** [comment]
Yeah, because some of our users, may try to start the new version ASAP when we release the new documentation, if they try via docker or k8s will raise error because we do not release docker image to dockerhub

**Review by zhongjiajie — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Congratulations and thanks @EricGao888

**Pull request merged**
