### PR TITLE
[Docs] Change about dolphinscheduler faq.md

### PR DESCRIPTION
**Pull request by jj551**
Signed-off-by: kodalien <kkodalien@gmail.com>

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Will review today later

**Comment by zhongjiajie** [comment]
Hi @Kodalien, it seem this PR have conflict

**Comment by zhongjiajie** [comment]
Could your rebase to master, solve conflict and force push to Github?

**Comment by zhongjiajie** [comment]
ping @Kodalien are you still working on this PR now

**Comment by Kodalien** [comment]
> ping @Kodalien你现在还在做这个 PR

of course @zhongjiajie

**Comment by Kodalien** [comment]
> ping @Kodalien你现在还在做这个 PR

of course @zhongjiajie

**Comment by zhongjiajie** [comment]
Looking forward your contribution

**Comment by zhongjiajie** [comment]
Hi @Kodalien since we migrate our docs into apache/dolphinscheduler in PR https://github.com/apache/dolphinscheduler/pull/9291, you should change this file in https://github.com/apache/dolphinscheduler/tree/dev/docs instead of apache/dolphinscheduler-website. Do you have time to migrate it to apache/dolphinscheduler? If you need some help, feel free to ping me.

**Comment by Kodalien** [comment]
> Hi @Kodalien since we migrate our docs into apache/dolphinscheduler in PR [apache/dolphinscheduler#9291](https://github.com/apache/dolphinscheduler/pull/9291), you should change this file in https://github.com/apache/dolphinscheduler/tree/dev/docs instead of apache/dolphinscheduler-website. Do you have time to migrate it to apache/dolphinscheduler? If you need some help, feel free to ping me.

Hi,borther ! Thanks, can assign my new PR！！easy to migrate DS document  @zhongjiajie

**Comment by zhongjiajie** [comment]
Hi @Kodalien , you could submit a PR to apache/dolphinscheduler directly, and I will review the docs PR

**Pull request closed without merging**
