### PR TITLE
[Docs] Add re-upload to resource center

### PR DESCRIPTION
**Pull request by calvinjiang**
https://github.com/apache/dolphinscheduler/pull/8359

### CODE REVIEW

**Review by zhuangchong — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
Hi @calvinjiang please just use the English version picture here. ZH and EN doc could just use the English one

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
waiting CI

**Comment by zhongjiajie** [comment]
Thanks

**Pull request merged**
