### PR TITLE
Fix format and typo in 1.3.9 Doc

### PR DESCRIPTION
**Pull request by RedemptionC**
1. In this doc,these two lines are decorated with h5 title,which seems a little weird,maybe bold-face works better here.
image
2. this line seems to be a typo:
```
Server基于netty提供监听服务。Worker
```
I changed it to:
```
WorkerServer基于netty提供监听服务。
```
Please correct me if that's not true

### CODE REVIEW

**Comment by RedemptionC** [comment]
@CalvinKirs @lenboo @dailidong please take a look

**Comment by RedemptionC** [comment]
It seems that many versions of doc are written this way,but I think case 1 maybe be a convention,while case 2 just doesn't really make sense👀

**Review by zhuangchong — APPROVED** [review]
+1

**Comment by RedemptionC** [comment]
@zhuangchong thanks for your review! 
BTW, I want to confirm this:
image
is this modification reasonable? I don't really know how the workerServer work, I just try to make it sound right grammatically

**Comment by zhuangchong** [comment]
@RedemptionC 
the maser-server sends tasks to the worker-server through netty.

**Comment by dailidong** [comment]
good job

**Comment by zhongjiajie** [comment]
Hi, @RedemptionC @zhuangchong @dailidong When changing doc, please make sure we change all document in all versions, in this patch we should also change version `1.3.1 - 1.3.8` and `dev` document. @RedemptionC Do you have a time   to add another PR to fix them?

**Comment by RedemptionC** [comment]
Hi, @zhongjiajie 
I've noticed that many versions of 1.3.x Doc are written this way
In fact,I was intending to ask advice on modification so that I can change all of them if my understanding on this modification is true
But somehow it was merged directly

**Comment by zhongjiajie** [comment]
> Hi, @zhongjiajie I've noticed that many versions of 1.3.x Doc are written this way In fact,I was intending to ask advice on modification so that I can change all of them if my understanding on this modification is true But somehow it was merged directly

Ok, then maybe you could submit new PR to correct them. One more things, we just release 202 document, you should also change 2.0.2 doc as well, thank 🎉  @RedemptionC

**Comment by RedemptionC** [comment]
@zhongjiajie 
The point is advice.
Actually,I'm learning DS via this Doc. Considering my knowledge on DS,I can only recognize obvious typo.When it comes to confusion about the internals,I raised  questions.
Perhaps the doc should be maintained by expert instead of someone just gets started. Or rather,it seems that confusions about the internals should be clarified by expert,rather than studying the code.
After all,the starting point of learning a project is the Doc instead of  the code,in my opinon.

**Comment by zhongjiajie** [comment]
> The point is advice.

@RedemptionC  Yeah, I got this, if you're the user or you start to learn DolphinScheduler, you should learn our document. If you found our doc has wrong content(I mean maybe our UI without the element, can not do something like doc, or maybe have misleading) you could just create a new issue in https://github.com/apache/dolphinscheduler/issues.

And, Yes, you're right, we should export as more detail as possible in our document, but not in codebase, we are trying but  it seems our maintainer do not have enough time to do it, So we help community could helping, we create todo list in https://github.com/apache/dolphinscheduler/issues/6535, feel free to take it if you want to build our community together

**Comment by zhongjiajie** [comment]
@RedemptionC If you need help or advice when you create issue or PR, feel free to ping me, I would reply ASAP

**Comment by RedemptionC** [comment]
Hi, @zhongjiajie 
Yes,I'd like to help improve the Docs.
But as I don't know much about DS internal,I have to learn from the docs(if not the code),during which I did have some questions.
For example:
1.
https://github.com/apache/dolphinscheduler-website/pull/618#issuecomment-1005463666 
I made this modification to make this sentence sound smoothly,but I don't know if it's the truth,i.e.,is workerServer providing listening servive based on netty?
https://github.com/apache/dolphinscheduler-website/pull/618#issuecomment-1005468955
Though @zhuangchong gave some explanation,it seems that my question isn't answered directly. Maybe it's due to that I'm not familiar with netty and I should learn it,but the reality is that I still don't  know whether this modification makes sense.
2.  https://github.com/apache/dolphinscheduler/discussions/7835
3.  https://github.com/apache/dolphinscheduler/discussions/7306

**Comment by SunnyZ-L** [comment]
> Hi, @zhongjiajie Yes,I'd like to help improve the Docs. But as I don't know much about DS internal,I have to learn from the docs(if not the code),during which I did have some questions. For example: 1. [#618 (comment)](https://github.com/apache/dolphinscheduler-website/pull/618#issuecomment-1005463666) I made this modification to make this sentence sound smoothly,but I don't know if it's the truth,i.e.,is workerServer providing listening servive based on netty? [#618 (comment)](https://github.com/apache/dolphinscheduler-website/pull/618#issuecomment-1005468955) Though @zhuangchong gave some explanation,it seems that my question isn't answered directly. Maybe it's due to that I'm not familiar with netty and I should learn it,but the reality is that I still don't know whether this modification makes sense. 2. [apache/dolphinscheduler#7835](https://github.com/apache/dolphinscheduler/discussions/7835) 3. [apache/dolphinscheduler#7306](https://github.com/apache/dolphinscheduler/discussions/7306)

>#618 (comment)
I made this modification to make this sentence sound smoothly,but I don't know if it's the truth,i.e.,is workerServer providing listening servive based on netty?

Your modification is correct, the original document should be a clerical error

**Comment by zhongjiajie** [comment]
Thanks @SunnyZ-L for the clarification. cc @RedemptionC

**Comment by zhongjiajie** [comment]
FYI @RedemptionC @SunnyZ-L , up to now, our document has many mistake/misleading. I and my team try to make our document more efficient and correct. But it seems we need more help from the community. Cause we do not have enough time to find and correct all our documents.

The only thing I could do is record all issues related to doc in https://github.com/apache/dolphinscheduler/issues/6535. And correct some emergencies. But we could not do all the things, at least at this time. So I hope someone could give some help.

**Comment by zhongjiajie** [comment]
BTW, I add two issue you said above to apache/dolphinscheduler#6535 too.

**Comment by zhongjiajie** [comment]
@SunnyZ-L What a good news, thanks and looking forward your contribution.

**Pull request merged**
