### PR TITLE
add doc of taskgoup

### PR DESCRIPTION
**Pull request by wangxj3**
add doc of taskgoup

### CODE REVIEW

**Comment by caishunfeng** [comment]
please add the English doc for TGQ.

**Comment by zhongjiajie** [comment]
Is this feature only exists in dev branch for now? @wangxj3 @caishunfeng

**Comment by wangxj3** [comment]
> Is this feature only exists in dev branch for now? @wangxj3 @caishunfeng



> 

yes

**Review by caishunfeng — APPROVED** [review]
LGTM

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks

**Pull request merged**
