### PR TITLE
[community] Update team member

### PR DESCRIPTION
**Pull request by zhongjiajie**
Add new committer and PMC member

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Please make sure your personal information is correct @songjianet @nielifeng @nobolity @jieguangzhou

**Comment by jieguangzhou** [comment]
> Please make sure your personal information is correct @songjianet @nielifeng @nobolity @jieguangzhou

My personal information is correct, thanks

**Review by jieguangzhou — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
thanks

**Pull request merged**
