### PR TITLE
[Feture 5752]Add blocking task type

### PR DESCRIPTION
**Pull request by mgsky1**
This PR contains Blocking task description writen in chinese and english.

You can refer: [PR #6272](https://github.com/apache/dolphinscheduler/pull/6272) and [Issue #5752](https://github.com/apache/dolphinscheduler/issues/5752) in DS main repo for more infomation about blocking task.

### CODE REVIEW

**Comment by mgsky1** [comment]
There are no images, because the front-end side has not been writen.😂 I just write a demo page for testing and not make a pull request.

**Comment by caishunfeng** [comment]
> There are no images, because the front-end side has not been writen.joy I just write a demo page for testing and not make a pull request.

Hi @mgsky1 I think you should add the front-end side together to keep the complete feature. 
BTW, DS will use the Next UI for upgrading, so you should develop in the Next UI for new feature.

**Comment by zhongjiajie** [comment]
@songjianet Do we have a plan to add this type task

**Comment by mgsky1** [comment]
> @songjianet Do we have a plan to add this type task

This is a [Summer 2021](https://summer.iscas.ac.cn/#/org/prodetail/210290130?lang=chi) project

**Comment by songjianet** [comment]
For the old UI, this work will not be supported, but it can be implemented in the new UI, but due to scheduling reasons, we may not support it in a short period of time, if you can handle the front end If so, you can handle it yourself, but it is still unknown when this feature will be officially released.

**Comment by zhongjiajie** [comment]
I got it, maybe we should merge task docs without screenshots and UI this time

**Comment by zhongjiajie** [comment]
@Tianqi-Dotes Could you please take a look in this English version docs?

**Comment by caishunfeng** [comment]
> I got it, maybe we should merge task docs without screenshots and UI this time

I don't think so, users can't use blocking task types due to lack of UI, so why wait for UI to be ready and then add this document?

**Comment by zhongjiajie** [comment]
I change my mind and waiting for ui, I add the label `missing-ui` on this PR, waiting for UI. Thank @caishunfeng

**Comment by zhongjiajie** [comment]
Hi @mgsky1  since we migrate our docs into apache/dolphinscheduler in PR https://github.com/apache/dolphinscheduler/pull/9291, you should change this file in https://github.com/apache/dolphinscheduler/tree/dev/docs instead of apache/dolphinscheduler-website. Do you have time to migrate it to apache/dolphinscheduler? If you need some help, feel free to ping me.

**Comment by mgsky1** [comment]
> Hi @mgsky1 since we migrate our docs into apache/dolphinscheduler in PR [apache/dolphinscheduler#9291](https://github.com/apache/dolphinscheduler/pull/9291), you should change this file in https://github.com/apache/dolphinscheduler/tree/dev/docs instead of apache/dolphinscheduler-website. Do you have time to migrate it to apache/dolphinscheduler? If you need some help, feel free to ping me.

Sorry for replying this comment so late. I am busy with graduating. I would like to know if this project is very urgent. If not, I can finish this task.

**Comment by zhongjiajie** [comment]
Looking forward about the change, currently you should change the document in path https://github.com/apache/dolphinscheduler/tree/dev/docs/docs instead of repo website , because to already migrate our doc to apache/dolphinscheduler now

**Comment by mgsky1** [comment]
> Looking forward about the change, currently you should change the document in path https://github.com/apache/dolphinscheduler/tree/dev/docs/docs instead of repo website , because to already migrate our doc to apache/dolphinscheduler now

Got it ~

**Comment by mgsky1** [comment]
The UI and doc development has been completed. [PR#10397](https://github.com/apache/dolphinscheduler/pull/10397)
@zhongjiajie

**Pull request closed without merging**
