### PR TITLE
add two blog

### PR DESCRIPTION
**Pull request by pinkfloyds**
add two blog  https://mp.weixin.qq.com/s/J9khVLDzNj1T1PqBmiqscw  https://mp.weixin.qq.com/s/PWo5EC0Alf2tA5oxzr_gdA

### CODE REVIEW

**Review by zhongjiajie — COMMENTED** [review]
Seem you do not add any content for this PR, could you add article doc for it?

**Comment by pinkfloyds** [comment]
see this commit [https://github.com/apache/dolphinscheduler-website/pull/943/commits/39721775cae26e665ba7283ecb74b406ab2ec85b](url)
I add two link from offical account of wechat

**Comment by zhongjiajie** [comment]
> see this commit https://github.com/apache/dolphinscheduler-website/pull/943/files
> I add two link from offical account of wechat

I know what you did, but I think our website should hold the article content, instead of linking to other websites, cause we do not how long they will keep the contents, so self-hosts content is the best choose

**Comment by pinkfloyds** [comment]
Thanks for your reply,I hive submited article file,and README.md modification I will create another PR

**Comment by zhongjiajie** [comment]
let wait CI run result

**Review by zhongjiajie — APPROVED** [review]

**Pull request merged**
