### PR TITLE
Fix hyperlink error

### PR DESCRIPTION
**Pull request by linjicong**
Fix hyperlink 404 error

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@linjicong Could you paste the link you found 404, I could not find this link

**Comment by linjicong** [comment]
https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/quick-start.html
https://dolphinscheduler.apache.org/zh-cn/development/backend-development.html

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
@linjicong Thanks for your contribution.

**Pull request merged**
