### PR TITLE
[FIX] [WEBSITE-9224] fix wechat CN and EN documents

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**
fix wechat CN and EN documents

### CODE REVIEW

**Comment by Tianqi-Dotes** [comment]
@caishunfeng PTAL at the CN version, have added image illustrations. Much appreciated.

**Comment by Tianqi-Dotes** [comment]
@zhongjiajie  PTAL at the EN version. Much appreciated.

**Review by zhongjiajie — COMMENTED** [review]
Looking good, but could you please change the picture to the English version? I find `enterprise-webchat-app-msg.png` and `enterprise-wechat-create-group.png` content Chinses content

**Comment by zhongjiajie** [comment]
> @zhongjiajie PTAL at the EN version. Much appreciated.

tips you're committer now, and you could require team members(committer or PMC) to review specific PR or issues, which you could see in. Personally, I will see our team required firstly when I browse github notification
image

**Review by caishunfeng — COMMENTED** [review]
LGTM, but the ds alert screenshot is missing, I think it's better to wait for the UI part to be ready and add the ds screenshot. What do you think?

**Comment by Tianqi-Dotes** [comment]
> LGTM, but the ds alert screenshot is missing, I think it's better to wait for the UI part to be ready and add the ds screenshot. What do you think?

Will add ds screenshot after done change the json format.

**Comment by Tianqi-Dotes** [comment]
> Looking good, but could you please change the picture to the English version? I find `enterprise-webchat-app-msg.png` and `enterprise-wechat-create-group.png` content Chinses content
Will do

**Comment by zhongjiajie** [comment]
I add the label `missing-ui` based on https://github.com/apache/dolphinscheduler-website/pull/751#pullrequestreview-924549605, mean this PR could not be merge unless we add UI part to it. Am I right?

**Comment by Tianqi-Dotes** [comment]
> I add the label `missing-ui` based on [#751 (review)](https://github.com/apache/dolphinscheduler-website/pull/751#pullrequestreview-924549605), mean this PR could not be merge unless we add UI part to it. Am I right?

Dear Jiajie,
You are right, will merge this doc after done the UI changes, refer to these issue:
https://github.com/apache/dolphinscheduler/issues/9235
https://github.com/apache/dolphinscheduler/issues/9311
Yours

**Comment by zhongjiajie** [comment]
Hi @Tianqi-Dotes, since we migrate our docs into apache/dolphinscheduler in PR https://github.com/apache/dolphinscheduler/pull/9291, you should change this file in https://github.com/apache/dolphinscheduler/tree/dev/docs instead of apache/dolphinscheduler-website. Do you have time to migrate it to apache/dolphinscheduler? If you need some help, feel free to ping me.

**Comment by Tianqi-Dotes** [comment]
have moved to new PR 
refer to https://github.com/apache/dolphinscheduler/pull/9439

**Pull request closed without merging**
