### PR TITLE
Add new release doc for 2.0.3

### PR DESCRIPTION
**Pull request by zhongjiajie**

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I am not pretty sure PR https://github.com/apache/dolphinscheduler/pull/7675 mean like dc2adf05. Could you please take a look on it? @caishunfeng

**Comment by caishunfeng** [comment]
> I am not pretty sure PR [apache/dolphinscheduler#7675](https://github.com/apache/dolphinscheduler/pull/7675) mean like [dc2adf0](https://github.com/apache/dolphinscheduler-website/commit/dc2adf05e3c6ce0548fc0f2964adb3077d9f4a42). Could you please take a look on it? @caishunfeng

Yes, that's right.

**Review by caishunfeng — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Document is ready, and we could merge whenever we need.

**Review by zhuangchong — APPROVED** [review]
+1

**Pull request merged**
