### PR TITLE
Translate ambari integration articles.

### PR DESCRIPTION
**Pull request by lukairui**
Translate ambari integration articles.

### CODE REVIEW

**Review by zhongjiajie — APPROVED** [review]
LGTM. cc @CalvinKirs @lenboo @dailidong

**Comment by CalvinKirs** [comment]
Have you tested this? As far as I know, it seems that ambari 2.0 has not been upgraded and may not be applicable.

**Comment by zhongjiajie** [comment]
> Have you tested this? As far as I know, it seems that ambari 2.0 has not been upgraded and may not be applicable.

No, I am not, I think this only a translate task for website repo.  😭

**Comment by zhongjiajie** [comment]
@lukairui Our community still have many task to do, maybe you could find in https://github.com/apache/dolphinscheduler/issues/5689 for code, and https://github.com/apache/dolphinscheduler/issues/6535 for document.

**Pull request closed without merging**
