### PR TITLE
[Docs] Change about dolphinscheduler kunernetes.md

### PR DESCRIPTION
**Pull request by Kodalien**
Signed-off-by: kodalien <kkodalien@gmail.com>

### CODE REVIEW

**Comment by zhongjiajie** [comment]
ping @Kodalien, are you still work on this PR now?

**Comment by zhongjiajie** [comment]
Hi @Kodalien  since we migrate our docs into apache/dolphinscheduler in PR https://github.com/apache/dolphinscheduler/pull/9291, you should change this file in https://github.com/apache/dolphinscheduler/tree/dev/docs instead of apache/dolphinscheduler-website. Do you have time to migrate it to apache/dolphinscheduler? If you need some help, feel free to ping me.

**Comment by Kodalien** [comment]
> 嗨@Kodalien ，因为我们将文档迁移到 PR [apache/dolphinscheduler#9291中的 apache/dolphinscheduler 中，您应该在](https://github.com/apache/dolphinscheduler/pull/9291)https://github.com/apache/dolphinscheduler/tree/dev/docs中更改此文件，而不是 apache/dolphinscheduler-website . 你有时间将它迁移到 apache/dolphinscheduler 吗？如果您需要帮助，请随时 ping 我。

this is a great operation,Thanks a lot for remembering me！！ @zhongjiajie

**Comment by Kodalien** [comment]
> > 嗨@Kodalien，因为我们将文档迁移到 PR [apache/dolphinscheduler#9291 中的 apache/dolphinscheduler 中，您应该在](https://github.com/apache/dolphinscheduler/pull/9291)[https://github.com/apache/dolphinscheduler/tree/dev/docs 中更改此文件，而不是](https://github.com/apache/dolphinscheduler/tree/dev/docs%E4%B8%AD%E6%9B%B4%E6%94%B9%E6%AD%A4%E6%96%87%E4%BB%B6%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF)apache/dolphinscheduler-网站。您有时间将它迁移到 apache/dolphinscheduler 吗？如果您需要帮助，请随时 ping 我。
> 
> 这是一次很棒的手术，非常感谢你记得我！！@zhongjiajie

directly assign to me，recently I submitted PR ！@zhongjiajie

**Pull request closed without merging**
