### PR TITLE
[refactor] Migrate docs to history branch

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Migrate all exists docs to branch `history-docs`
* Add build script to fetch history docs or from main
  repository
* Change CI workflow

### CODE REVIEW

**Comment by zhongjiajie** [comment]
We will merge this PR tonight at 22:00(UTC+8) for safety

**Review by songjianet — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
This PR can not be merged after we merged #757  😭

**Review by CalvinKirs — APPROVED** [review]
well done

**Comment by zhongjiajie** [comment]
We start the first shot, right here right now.

**Pull request merged**
