### PR TITLE
[Feature][Task] Add Data Quality Task Zh Doc

### PR DESCRIPTION
**Pull request by zixi0825**
Add Data Quality Task Zh Doc

### CODE REVIEW

**Comment by caishunfeng** [comment]
@zhongjiajie Is it possible to submit Zh doc first?

**Comment by zhongjiajie** [comment]
Better submit EN and ZH doc together. BTW, system screenshots should use EN instead of ZH

**Comment by dailidong** [comment]
@zixi0825 good job, 



> submit EN

+1

@zixi0825 , good job, it is such a big feature, can you also submit a English version doc for data quality?

**Comment by zixi0825** [comment]
> @zixi0825 good job,
> 
> > submit EN
> 
> +1
> 
> @zixi0825 , good job, it is such a big feature, can you also submit a English version doc for data quality?

I will submit it in this weekend

**Comment by zhongjiajie** [comment]
Hi @zixi0825  since we migrate our docs into apache/dolphinscheduler in PR https://github.com/apache/dolphinscheduler/pull/9291, you should change this file in https://github.com/apache/dolphinscheduler/tree/dev/docs instead of apache/dolphinscheduler-website. Do you have time to migrate it to apache/dolphinscheduler? If you need some help, feel free to ping me.

**Comment by zhongjiajie** [comment]
Hi @zixi0825 do you have time to submit a PR to apache/dolphinscheduler to finish data quality docs? we plan to release `3.0.3-alpha` be we without data quality docs now.

**Comment by davidzollo** [comment]
I noticed that this doc already exists in the website[1], I will close this PR

1, https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/data-quality.html

**Pull request closed without merging**
