### PR TITLE
Simply refactor document for DolphinScheduler 2.0

### PR DESCRIPTION
**Pull request by zhongjiajie**

### CODE REVIEW

**Comment by zhongjiajie** [comment]
It ready to go now, I add screenshot of it.
@lenboo  It a little be different to our discussion, I do not think we should add sub directory to keep our `homepage` `resource center` and `datasource center`. Cause it'll make our document too deep.

So I just change title from `homepage` to `workflow overview` as @caishunfeng suggestion, I think this make sense more than `homepage`

WDYT

image

**Comment by lenboo** [comment]
> It ready to go now, I add screenshot of it. @lenboo It a little be different to our discussion, I do not think we should add sub directory to keep our `homepage` `resource center` and `datasource center`. Cause it'll make our document too deep.
> 
> So I just change title from `homepage` to `workflow overview` as @caishunfeng suggestion, I think this make sense more than `homepage`
> 
> WDYT
> 
> image

good!  Maybe you are right!

**Review by lenboo — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
Thanks for merging, I found out there have some error in our doc dev tab leading page, and I submit new PR #454 to fix it.

**Pull request merged**
