### PR TITLE
Fixed some broken hyperlinks

### PR DESCRIPTION
**Pull request by lukairui**
Fixed some broken hyperlinks

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Patch look good to me, but we still have to add this change to dev directory, you could find more detail in https://github.com/apache/dolphinscheduler-website/pull/494#issuecomment-955143992

**Comment by lukairui** [comment]
OK , I have resubmitted.

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
