### PR TITLE
[fix][scripts]: prepare_docs.sh supports image path conversion.

### PR DESCRIPTION
**Pull request by huangchenguang123**
Since viewing md on github requires a relative path, use '../../../../'.

so it will convert img path and make them work bot github markdown and website.

see my code in https://github.com/apache/dolphinscheduler/pull/10127

### CODE REVIEW

**Comment by huangchenguang123** [comment]
Please review my code @zhongjiajie .Thanks.

**Comment by zhongjiajie** [comment]
Did you test locally? @huangchenguang123

**Comment by huangchenguang123** [comment]
> Did you test locally? @huangchenguang123

Yes, I tested locally. Is there something wrong with the code?

**Comment by zhongjiajie** [comment]
No, I just make sure about it, but is seem we do not change the img path in apache/dolphinscheculer, should we also change the path related path in directory `docs` in apache/dolphinscheculer?

**Comment by huangchenguang123** [comment]
> No, I just make sure about it, but is seem we do not change the img path in apache/dolphinscheculer, should we also change the path related path in directory `docs` in apache/dolphinscheculer?

If the documentation wants to be previewed in github/idea, the image path in docs should be changed. like https://github.com/apache/dolphinscheduler/pull/10127. To be compatible with the website, the path needs to be rewritten in the script.From '../../../../img' to '/img'.I don't know if you understand what I mean?

**Comment by huangchenguang123** [comment]
Did I should do someting more? @zhongjiajie

**Comment by zhongjiajie** [comment]
> 

@huangchenguang123  It is my bad, I am working hard on the issue of the 3.0.0-beta-1 release process. I will take a look at this issue after the version release.

**Comment by huangchenguang123** [comment]
> > 
> 
> @huangchenguang123 It is my bad, I am working hard on the issue of the 3.0.0-beta-1 release process. I will take a look at this issue after the version release.

Thanks.

**Comment by zhongjiajie** [comment]
> > > 
> > 
> > 
> > @huangchenguang123 It is my bad, I am working hard on the issue of the 3.0.0-beta-1 release process. I will take a look at this issue after the version release.
> 
> Thanks.

will task a look tonight or tomorrow, we need more local tests about it

**Comment by zhongjiajie** [comment]
> > > 
> > 
> > 
> > @huangchenguang123 It is my bad, I am working hard on the issue of the 3.0.0-beta-1 release process. I will take a look at this issue after the version release.
> 
> Thanks.

will task a look tonight or tomorrow, we need more local tests about it

**Comment by zhongjiajie** [comment]
I have checked this PR and it works fine except some comment issues and I have already fixed them in 
9703931

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks

**Comment by zhongjiajie** [comment]
Well done and thanks @huangchenguang123

**Pull request merged**
