### PR TITLE
feat: Support python multiple version documents

### PR DESCRIPTION
**Pull request by zhongjiajie**
* We use the repo in swap/dolphinscheduler to build all python versions docs
* Remove exists `build-py-doc` step
* Copy all python version docs into dist/python directory

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Do not merge until https://github.com/apache/dolphinscheduler/pull/11391 merged

**Review by SbloodyS — APPROVED** [review]

**Comment by zhongjiajie** [comment]
👍 the fastest man in dolphinscheduler community 👍 @SbloodyS

**Comment by EricGao888** [comment]
> 👍 the fastest man in dolphinscheduler community 👍 @SbloodyS

@zhongjiajie @SbloodyS 🚀 SbloodyS 🚀 is a DS community super hero with the name of `FASTMAN`.

**Comment by SbloodyS** [comment]
WTF.... I don't want to be the `FASTMAN`...

**Pull request merged**
