### PR TITLE
[FIX] [WEBSITE-9279] fix parameter priority documentation

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**
fix parameter priority documentation

### CODE REVIEW

**Comment by Tianqi-Dotes** [comment]
The author of this PR is @wangxj3 , thanks to the contribution.

**Comment by Tianqi-Dotes** [comment]
I will do the EN version fix when CN version review is done.

**Review by caishunfeng — COMMENTED** [review]
zh-cn is OK.

**Review by zhongjiajie — APPROVED** [review]
LGTM

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks

**Pull request merged**
