### PR TITLE
updated en-us.json and zh-cn.json

### PR DESCRIPTION
**Pull request by buwenbuhuo97**
DolphinScheduler Misspelling

### CODE REVIEW

**Comment by EricGao888** [comment]
Hello @buwenbuhuo97 , why did u close this PR?

**Comment by buwenbuhuo97** [comment]
dolphinscheduler Misspelling

**Comment by EricGao888** [comment]
> dolphinscheduler Misspelling

That's the reason why u had opened this PR. I'm curious about why u closed it.

**Comment by buwenbuhuo97** [comment]
> 
Sorry to submit pr for the first time

**Comment by buwenbuhuo97** [comment]
> > dolphinscheduler 拼写错误
> 
> 这就是您打开此 PR 的原因。我很好奇你为什么关闭它。



> > dolphinscheduler Misspelling
> 
> That's the reason why u had opened this PR. I'm curious about why u closed it.

Sorry to submit pr for the first time

**Pull request closed without merging**
