### PR TITLE
[ci] Add CI failed when any change in docs

### PR DESCRIPTION
**Pull request by zhongjiajie**

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I test the failed test case in https://github.com/apache/dolphinscheduler-website/runs/5798852002?check_suite_focus=true and it success

**Review by songjianet — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks~

**Comment by zhongjiajie** [comment]
I had test in PR https://github.com/apache/dolphinscheduler-website/pull/758 and it work

**Pull request merged**
