### PR TITLE
[Fix-7668][docs] Fix Modify the prompt message of MySQL driver version

### PR DESCRIPTION
**Pull request by SunnyZ-L**
this closes #7668

### CODE REVIEW

**Comment by RedemptionC** [comment]
what does #7668 refer to ?

**Review by dailidong — APPROVED** [review]
+1
good job

**Comment by SunnyZ-L** [comment]
> what does #7668 refer to ?

Document-related issues are maintained in the main library(https://github.com/apache/dolphinscheduler/issues), 7669 is an issue in the main library

**Comment by RedemptionC** [comment]
> > what does #7668 refer to ?
> 
> Document-related issues are maintained in the main library(https://github.com/apache/dolphinscheduler/issues), 7669 is an issue in the main library

Oh I got it. I wondered why this repo doesn't have a issue section once

**Comment by zhongjiajie** [comment]
> > what does #7668 refer to ?
> 
> Document-related issues are maintained in the main library(https://github.com/apache/dolphinscheduler/issues), 7669 is an issue in the main library

@SunnyZ-L @RedemptionC  FYI, If you link issue with different repository, you have to use full URL path `https://github.com/apache/dolphinscheduler/issues/7668` instead of short link `#7668`, eg, 
https://github.com/apache/dolphinscheduler/issues/7668

**Comment by SunnyZ-L** [comment]
> > > what does #7668 refer to ?
> > 
> > 
> > Document-related issues are maintained in the main library(https://github.com/apache/dolphinscheduler/issues), 7669 is an issue in the main library
> 
> @SunnyZ-L @RedemptionC FYI, If you link issue with different repository, you have to use full URL path `https://github.com/apache/dolphinscheduler/issues/7668` instead of short link `#7668`, eg, [apache/dolphinscheduler#7668](https://github.com/apache/dolphinscheduler/issues/7668)

ok, Next time I will use the full issue link

**Pull request merged**
