### PR TITLE
[release] New release for version 300

### PR DESCRIPTION
**Pull request by zhongjiajie**

### CODE REVIEW

**Comment by zhongjiajie** [comment]
do not merge until https://github.com/apache/dolphinscheduler/pull/11356 merged

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
dead link due to #820

**Comment by zhongjiajie** [comment]
Also exist in version dev https://github.com/apache/dolphinscheduler/pull/11363 and version 3.0.0 https://github.com/apache/dolphinscheduler/commit/baa59f28c7d790d1d3cdb6f7f970b6f7cdd9659e

**Review by SbloodyS — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Finally !!!!

**Pull request merged**
