### PR TITLE
[release] New version doc 205 release

### PR DESCRIPTION
**Pull request by zhongjiajie**
Add new release doc 204

### CODE REVIEW

**Comment by zhongjiajie** [comment]
The dead link checker failed. because 204 still not release 

```log
[✖] https://downloads.apache.org/dolphinscheduler/2.0.4/apache-dolphinscheduler-2.0.4-src.tar.gz.asc → Status: 404
[✖] https://downloads.apache.org/dolphinscheduler/2.0.4/apache-dolphinscheduler-2.0.4-src.tar.gz.sha512 → Status: 404
[✖] https://downloads.apache.org/dolphinscheduler/2.0.4/apache-dolphinscheduler-2.0.4-bin.tar.gz.asc → Status: 404
[✖] https://downloads.apache.org/dolphinscheduler/2.0.4/apache-dolphinscheduler-2.0.4-bin.tar.gz.sha512 → Status: 404
```

**Comment by zhongjiajie** [comment]
I had commented in https://github.com/apache/dolphinscheduler/pull/8359#issuecomment-1055030282. If we can not add it to this PR, we would add in separate PR

**Comment by zhongjiajie** [comment]
should pick from #710

**Comment by zhongjiajie** [comment]
This PR is ready to go now @lenboo @JinyLeeChina

**Comment by zhongjiajie** [comment]
CI failed due to we do not have release content in `2.0.5` directory

**Review by JinyLeeChina — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
CI green, PTAL @JinyLeeChina

**Review by JinyLeeChina — APPROVED** [review]
+1

**Pull request merged**
